### ISSUE TITLE
Access Of Field in C++ Queries (Copy from LGTM please)

### ISSUE THREAD

**Issue by hdthinh1012test** [codeql-agent-project/codeql-cheatsheet#33]
## Checklist
- [x] Did you check all the existing queries?
- [x] Is this problem reusable? If it is not, please ask for help in [CodeQL Discussion](https://github.com/github/codeql/discussions).

## Query information
- Language: C++

## Description
Finds reads of `aDate` (defined on class `Order`)

**Comment by hdthinh1012** [comment]
Fixed in 9ab35229d494775a16eac394a7712a71c0559c8d
