### ISSUE TITLE
Copy Request From LGTM (C/C++, Go, Python)

### ISSUE THREAD

**Issue by hdthinh1012** [codeql-agent-project/codeql-cheatsheet#36]
## Checklist
- [x] Did you check all the existing queries?
- [x] Is this problem reusable? If it is not, please ask for help in [CodeQL Discussion](https://github.com/github/codeql/discussions).

## Query information
- Language: C/C++, Go, Python
- 
## Description
Copy from [LGTM Query Console](https://lgtm.com/query/lang:csharp/) (Est: 4H work)

**Comment by vovikhangcdv** [comment]
Hi @hdthinh1012, we should use the **Blank** template and write a new one for the non-request issue.

**Comment by vovikhangcdv** [comment]
Look like this issue is duplicated by #5 .

**Comment by hdthinh1012** [comment]
> Look like this issue is duplicated by #5 .

Me and @L3on30 decides to split the init queries tasks and we didn't aware at the opened duplicate issues #5. So we decides to close #5 as duplicate and follow the new plan.
